### ISSUE TITLE
A easier usage

### ISSUE THREAD

**Issue by alexander-svendsen** [nutgaard/yet-another-fetch-mock#1]
When using javascript (not typescript) 
I want to be able to write my mock scenarios like so:

```js
mock.get(
    '/veilarboppfolging/api/oppfolging',
    ({ queryParams }) =>oppfolging(queryParams)
);
````

it almost works, i must now write them like so:

```js
mock.get(
    '/veilarboppfolging/api/oppfolging',
    ({ queryParams }) => ResponseUtils.jsonPromise(oppfolging(queryParams)
);
````

What do you think?

**Comment by nutgaard** [comment]
The test [here](https://github.com/nutgaard/yet-another-fetch-mock/commit/83a3f1606b772f5b51156dbf7869a8afa96e2d3e#diff-d0c4bfb6e8699318560d2e042b5a42c6R232) should be similar to your usecase.

**Comment by alexander-svendsen** [comment]
Nice :) 

the typescript comment was just me telling that i'm using the library in a plain javascript env :p 
and wanted to use it differently then the examples so far
